# Generated by Django 4.2.16 on 2024-11-16 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_ADD_CATEGORY'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a name of item.', max_length=30)),
                ('desc', models.TextField(help_text='Please describe information about your item.')),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], default='A', max_length=1)),
                ('start_price', models.DecimalField(decimal_places=2, help_text='Enter the starting bid should be.', max_digits=7)),
                ('image_url', models.URLField(blank=True, help_text='Please provide the URL of your item(optional).')),
                ('category', models.CharField(blank=True, choices=[], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
