# Generated by Django 4.2.16 on 2024-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_ADD_BID_CMNT_WATCHLIST'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('PNT', 'Paintings'), ('TOY', 'Toys')], max_length=3),
        ),
    ]
