# Generated by Django 4.2.16 on 2024-11-21 09:15
# note added by dev : Changed types of fields for Watchlist from ForeignKey to ManyToManyField

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_category_name_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='watched_by', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(related_name='watching_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
